remove term-missing

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -63,7 +63,6 @@ jobs:
         set -o pipefail
         pytest \
           -v \
-          --cov=esm \
           --cov-report=term \
           --cov-report=xml:coverage.xml \
           --junitxml=pytest.xml \
@@ -71,21 +70,21 @@ jobs:
           | tee pytest-coverage.txt
       shell: pixi run bash -e {0}
 
-    - name: Run Docker tests
-      env:
-        DOCKER_TAG: ${{ github.sha }}
-        FORGE_URL: https://forge.evolutionaryscale.ai/
-      run: |
-        set -e
-        cd tests
-        make build-oss-ci
-        make start-docker-oss URL=${{ env.FORGE_URL }} DOCKER_TAG=${{ env.DOCKER_TAG }} ESM3_FORGE_TOKEN=${{ secrets.ESM3_FORGE_TOKEN }}
-      shell: pixi run bash -e {0}
+    # - name: Run Docker tests
+    #   env:
+    #     DOCKER_TAG: ${{ github.sha }}
+    #     FORGE_URL: https://forge.evolutionaryscale.ai/
+    #   run: |
+    #     set -e
+    #     cd tests
+    #     make build-oss-ci
+    #     make start-docker-oss URL=${{ env.FORGE_URL }} DOCKER_TAG=${{ env.DOCKER_TAG }} ESM3_FORGE_TOKEN=${{ secrets.ESM3_FORGE_TOKEN }}
+    #   shell: pixi run bash -e {0}
 
-    - name: cleanup docker containers if they're hanging
-      if: ${{ always() }}
-      run: |
-          docker rm --force --volumes $(docker ps -q) || true
+    # - name: cleanup docker containers if they're hanging
+    #   if: ${{ always() }}
+    #   run: |
+    #       docker rm --force --volumes $(docker ps -q) || true
 
     # Next two steps adds a comment to any PR that reports tests + code coverage.
     - name: Pytest Coverage Comment
